name: filter_app
description: A powerful filter application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.0
  image_filter_plus: ^0.0.1
  path_provider: ^2.1.5
  share_plus: ^10.1.0
  image: ^4.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
